# Generated by Django 5.0.3 on 2024-05-16 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_user_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="country",
            field=models.CharField(default="India", max_length=255),
        ),
    ]
